# Generated by Django 2.2.6 on 2019-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='when',
            field=models.DateField(auto_now_add=True),
        ),
    ]
