# Generated by Django 2.2.6 on 2019-10-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20191019_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='when',
            field=models.DateField(),
        ),
    ]
