# Generated by Django 2.2.6 on 2019-11-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_meetup_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='question',
        ),
    ]
